# Generated by Django 4.1 on 2022-12-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEMINARIO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='participantes',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='hora_inscripcion',
            field=models.TimeField(),
        ),
    ]
